# Generated by Django 2.2.3 on 2020-05-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200504_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='set_password',
            new_name='user_password',
        ),
    ]
