# Generated by Django 2.2.3 on 2020-05-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200504_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_password',
            new_name='password',
        ),
    ]
